apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podpvc
  namespace: qq2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: qq2
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: podpvc
        readOnly: true
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: data
          readOnly: true

